---
- name: Prepare folders and clone git repo with compose files
  hosts: docker
  become: true
  vars:
    docker_dir: "/srv/docker"


  tasks:
      - name: Clone the Git repository
        git:
          repo: 'https://github.com/davidlesicnik/docker'
          dest: "{{ docker_dir }}"