---
- name: Configure different docker volume directory
  hosts: docker
  become: true
  tasks:
    - name: Add bind mount entry to /etc/fstab and mount
      ansible.builtin.mount:
        path: /var/lib/docker/volumes
        src: /mnt/ssd/volumes
        fstype: none
        opts: bind
        state: mounted
        passno: 2

    - name: Restart Docker to apply changes
      ansible.builtin.service:
        name: docker
        state: restarted
