---
- name: Setup access to docker system for Alloy
  hosts: docker
  become: true
  tasks:
    - name: Set alloy to run as root
      ansible.builtin.replace:
        path: /usr/lib/systemd/system/alloy.service
        regexp: 'User=alloy'
        replace: "User=root"

    - name: Add alloy user to docker group
      ansible.builtin.user:
        name: alloy
        groups: docker
        append: yes

    - name: Restart alloy service
      ansible.builtin.service:
        name: alloy
        state: restarted
        daemon_reload: yes
