---
- name: Install Docker
  hosts: docker
  gather_facts: false
  become: true
  tasks:
    - name: Install apt-transport-https
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true

    - name: Download Docker GPG key using curl
      ansible.builtin.command:
        cmd: "curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg -o /etc/apt/keyrings/docker.gpg"

    - name: Add Docker GPG key using apt-key
      ansible.builtin.command:
        cmd: "apt-key add /etc/apt/keyrings/docker.gpg"

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io 
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Create proxy network
      docker_network:
        name: proxy

    - name: Add david user to docker group
      ansible.builtin.user:
        name: david
        groups: docker
        append: yes

    - name: Add ansible user to docker group
      ansible.builtin.user:
        name: ansible
        groups: docker
        append: yes