---
- name: Start all Docker services in /srv/docker/
  hosts: docker
  gather_facts: false
  become: true
  vars_files:
  - ../../../vaults/int_vault

  tasks:
    - name: Copy plex env example 
      ansible.builtin.copy:
        src: /srv/docker/plex/.env.example
        dest: /srv/docker/plex/.env
        remote_src: yes

    - name: Replace "EXAMPLE" with the value provided
      ansible.builtin.replace:
        path: /srv/docker/plex/.env
        regexp: 'EXAMPLE'
        replace: "{{ plex }}"

    - name: Copy wireguard env example 
      ansible.builtin.copy:
        src: /srv/docker/wireguard/.env.example
        dest: /srv/docker/wireguard/.env
        remote_src: yes

    - name: Replace wireguard placeholder
      ansible.builtin.replace:
        path: /srv/docker/wireguard/.env
        regexp: 'EXAMPLE'
        replace: "{{ wireguard_pw }}"

    - name: Find all service directories with docker-compose files
      ansible.builtin.find:
        paths: /srv/docker/
        patterns: docker-compose.yml
        recurse: yes
      register: compose_files

    - name: Start each docker-compose service
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: "{{ item.path | dirname }}"
      loop: "{{ compose_files.files }}"
      loop_control:
        loop_var: item