---
- name: Start all Docker services in /srv/docker/
  hosts: docker
  gather_facts: false
  become: true
  vars_files:
  - ../../../vaults/int_vault

  tasks:
    - name: Configure plex env with templated file
      ansible.builtin.template:
        src: ../../../templates/docker/plex.env.j2
        dest: /srv/docker/plex/.env
        mode: '0644'
        force: yes 
      register: plex_env

    - name: Configure wireguard env with templated file
      ansible.builtin.template:
        src: ../../../templates/docker/wireguard.env.j2
        dest: /srv/docker/wireguard/.env
        mode: '0644'
        force: yes 
      register: wireguard_env

    - name: Configure immich env with templated file
      ansible.builtin.template:
        src: ../../../templates/docker/immich.env.j2
        dest: /srv/docker/immich/.env
        mode: '0644'
        force: yes 
      register: immich_env

    - name: Disable DNSStubListener in resolved.conf
      ansible.builtin.command:
      cmd: sudo sed -r -i.orig 's/#?DNSStubListener=yes/DNSStubListener=no/g' /etc/systemd/resolved.conf

    - name: Restart systemd-resolved service
      ansible.builtin.systemd:
      name: systemd-resolved
      state: restarted

    - name: Configure prometheus yml with templated file
      ansible.builtin.template:
        src: ../../../templates/docker/prometheus.yml.j2
        dest: /srv/docker/prometheus/prometheus.yml
        mode: '0644'
        force: yes 
      register: prometheus_env

    - name: Find all service directories with docker-compose files
      ansible.builtin.find:
        paths: /srv/docker/
        patterns: docker-compose.yml
        recurse: yes
      register: compose_files

    - name: Start each docker-compose service
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: "{{ item.path | dirname }}"
      loop: "{{ compose_files.files }}"
      loop_control:
        loop_var: item