---
- name: Setup hostname & network
  hosts: template
  become: true

  tasks:
    - name: Set hostname
      hostname:
        name: storage
        
    - name: Copy netplan config
      copy:
        src: ../../files/storage/00-installer-config.yaml
        dest: /etc/netplan/00-installer-config.yaml
        owner: root
        group: root
        mode: '700'

    - name: Apply new IP - 192.168.10.20
      command: netplan apply