---
- name: Install Grafana Alloy
  hosts: "{{ target_hosts | default('all') }}"
  become: true
  vars_files:
    - ../../vault

  tasks:
    - name: Install apt-transport-https
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true

    - name: Add signing key
      ansible.builtin.apt_key:
        url: "https://apt.grafana.com/gpg.key"
        state: present
        keyring: "/etc/apt/keyrings/grafana.gpg"

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main"
        state: present
        filename: grafana

    - name: Install Alloy
      ansible.builtin.apt:
        name:
          - alloy
        state: latest
        update_cache: true

    - name: Configure alloy with templated config file
      ansible.builtin.template:
        src: ../../templates/config.alloy.j2
        dest: /etc/alloy/config.alloy
        mode: '0644'

    - name: Restart and enable alloy service
      ansible.builtin.service:
        name: alloy
        state: restarted
        enabled: yes

