---
- name: Install Docker
  hosts: docker
  gather_facts: false
  become: true
  tasks:
    - name: Install apt-transport-https
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true

    - name: Download Grafana GPG key using curl
      ansible.builtin.command:
        cmd: "curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg -o /etc/apt/keyrings/docker.gpg"

    - name: Add Grafana GPG key using apt-key
      ansible.builtin.command:
        cmd: "apt-key add /etc/apt/keyrings/docker.gpg"

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: latest
        update_cache: true

    - name: Add david user to docker group
      ansible.builtin.user:
        name: david
        groups: docker
        append: yes