---
- import_playbook: ../../generic/setup_network.yml
  vars:
    new_hostname: "storage"
    new_ip: "192.168.10.20"
- import_playbook: ../../generic/update_apt.yml
  vars:
    target_hosts: storage
- import_playbook: ../../generic/setup_timezone.yml
  vars:
    target_hosts: storage
- import_playbook: setup_mount_hdd.yml
- import_playbook: setup_mount_ssd.yml
- import_playbook: setup_mount_external.yml
- import_playbook: setup_nfs.yml
- import_playbook: setup_samba.yml
- import_playbook: ../../generic/setup_restic.yml
  vars:
    target_hosts: storage
- import_playbook: ../../generic/setup_alloy.yml
  vars:
    target_hosts: storage
- import_playbook: ../../generic/reboot.yml
  vars:
    target_hosts: storage