---
- name: Setup Samba
  hosts: storage
  gather_facts: false
  become: true

  tasks:
  - name: Install Samba and related packages
    apt:
      name: samba
      state: present

  - name: Configure Samba global settings
    community.general.ini_file:
      path: /etc/samba/smb.conf
      section: "global"
      section_has_values:
      - option: "workgroup"
        value: "WORKGROUP"
      - option: "server string"
        value: "storage"
      - option: "netbios name"
        value: "storage"
      - option: "security"
        value: "user"
      - option: "map to guest"
        value: "bad user"
      - option: "dns proxy"
        value: "no"

  - name: Configure Samba media share settings
    community.general.ini_file:
      path: /etc/samba/smb.conf
      section: "media"
      section_has_values:
      - option: "path"
        value: "/mnt/hdd/media"
      - option: "browseable"
        value: "yes"
      - option: "writable"
        value: "yes"
      - option: "guest ok"
        value: "yes"
      - option: "read only"
        value: "no"
      - option: "force user"
        value: "david"
      - option: "force group"
        value: "david"
      - option: "create mask"
        value: "0660"
      - option: "directory mask"
        value: "0770"

  - name: Restart Samba services
    systemd:
      name: smbd
      state: restarted
      enabled: yes

  - name: Ensure the Samba service is running
    service:
      name: smbd
      state: started
      enabled: yes
