---
- name: Setup Samba
  hosts: storage
  gather_facts: false
  become: true

  tasks:
  - name: Install Samba and related packages
    apt:
      name: samba
      state: present

  - name: Configure Samba global settings with Ansible ini_file module
    ansible.builtin.ini_file:
      path: /etc/samba/smb.conf
      section: "global"
      options:
        workgroup: "WORKGROUP"
        server string: "storage"
        netbios name: "storage"
        security: "user"
        map to guest: "bad user"
        dns proxy: "no"

  - name: Configure Samba media share with Ansible ini_file module
    ansible.builtin.ini_file:
      path: /etc/samba/smb.conf
      section: "media"
      options:
        path: "/mnt/hdd/media"
        browseable: "yes"
        writable: "yes"
        guest ok: "yes"
        read only: "no"
        force user: "david"
        force group: "david"
        create mask: "0660"
        directory mask: "0770"

  - name: Restart Samba services
    systemd:
      name: smbd
      state: restarted
      enabled: yes

  - name: Ensure the Samba service is running
    service:
      name: smbd
      state: started
      enabled: yes
