---
- name: Setup initial HDD mount
  hosts: storage
  gather_facts: false
  become: true
  vars:
    mount_point: "/mnt/external"
    uuid: "3359fada-4793-453a-9801-6136ca3a3d48"
    filesystem_type: "xfs"
    mount_options: "defaults"
    fstab_options: "defaults,nofail 0 2"

  tasks:
  - name: Ensure the mount point directory exists
    file:
      path: "{{ mount_point }}"
      state: directory

  - name: Mount the filesystem
    mount:
      path: "{{ mount_point }}"
      src: "UUID={{ uuid }}"
      fstype: "{{ filesystem_type }}"
      opts: "{{ mount_options }}"
      state: mounted

  - name: Ensure the device is in fstab with nofail option
    lineinfile:
      path: /etc/fstab
      state: present
      regexp: "^UUID={{ uuid }}"
      line: "UUID={{ uuid }} {{ mount_point }} {{ filesystem_type }} {{ fstab_options }}"
