---
- name: Setup initial SSD mount
  hosts: storage
  become: true

  tasks:
    - name: Set hostname
      hostname:
        name: storage
        
    - name: Copy netplan config
      copy:
        src: ../../files/storage/00-installer-config.yaml
        dest: /etc/netplan/00-installer-config.yaml

    - name: Apply new IP - 192.168.10.20
      command: netplan apply