---
- name: Setup Samba
  hosts: storage
  gather_facts: false
  become: true
  
  tasks:
    - name: Install Samba and related packages
      apt:
        name: samba
        state: present

    - name: Copy smb config
      copy:
        src: ../../files/storage/smb.conf
        dest: /etc/samba/smb.conf

    - name: Restart Samba services
      systemd:
        name: smbd
        state: restarted
        enabled: yes

    - name: Ensure the Samba service is running
      service:
        name: smbd
        state: started
        enabled: yes
