---
- name: Install and configure NFS server
  hosts: storage
  gather_facts: false
  become: true

  vars:
    nfs_exports:
      - "/mnt/hdd *(rw,sync,no_subtree_check)"
      - "/mnt/ssd *(rw,sync,no_subtree_check)"
  tasks:
    - name: Install nfs
      apt:
        name: nfs-kernel-server
        state: present

    - name: Set ownership of /mnt/hdd and /mnt/ssd to nobody:nogroup
      file:
        path: "{{ item }}"
        owner: nobody
        group: nogroup
        state: directory
      loop:
        - /mnt/hdd
        - /mnt/ssd

    - name: Configure NFS exports
      lineinfile:
        path: /etc/exports
        line: "{{ item }}"
        state: present
      loop: "{{ nfs_exports }}"

    - name: Start and enable NFS service
      systemd:
        name: nfs-server
        state: started
        enabled: true

    - name: Export NFS shares
      command: exportfs -a