---
- name: Clone and start template
  hosts: pve
  become: true

  tasks:
    - name: Clone VM
      command: qm clone 900 {{ vmid }} --full --name {{ vm_name }}

    - name: Start VM
      command: qm start {{ vmid }}
  
    - name: Wait for 15 seconds after a boot
      pause:
        seconds: 15