---
- name: Update duckdns domain
  hosts: ansible
  gather_facts: false
  vars_files:
  - ../../../vaults/auto_vault
  vars:
    url: "https://www.duckdns.org/update?domains=lesicnik&token={{ duckdns_token }}&ip="

  tasks:
    - name: Update duckdns
      command: curl -k {{ url }}
