---
- name: Install and configure NFS server
  hosts: "{{ target_hosts | default('all') }}"
  become: true

  tasks:
    - name: Install restic
      apt:
        name: nfs-common
        state: present