---
- name: Setup hostname & network
  hosts: template
  gather_facts: false
  become: true

  tasks:
    - name: Set hostname
      hostname:
        name: storage
        
    - name: Copy netplan config
      copy:
        src: ../../files/generic/00-installer-config.yaml
        dest: /etc/netplan/00-installer-config.yaml
        owner: root
        group: root
        mode: '700'

    - name: Set IP address
      ansible.builtin.replace:
        path: /etc/netplan/00-installer-config.yaml
        regexp: 'PLACEHOLDER_IP'
        replace: "{{ ip }}"

    - name: Apply new IP
      command: netplan apply