---
- name: Install Alloy
  hosts: "{{ target_hosts | default('all') }}"
  become: true
  vars_files:
    - ../../vaults/int_vault

  tasks:
    - name: Install apt-transport-https
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true

    - name: Download Grafana GPG key using curl
      ansible.builtin.command:
        cmd: "curl -fsSL https://apt.grafana.com/gpg.key -o /etc/apt/keyrings/grafana.gpg"

    - name: Add Grafana GPG key using apt-key
      ansible.builtin.command:
        cmd: "apt-key add /etc/apt/keyrings/grafana.gpg"

    - name: Add Grafana repository 
      ansible.builtin.apt_repository:
        repo: "deb https://apt.grafana.com stable main"
        state: present
        filename: grafana

    - name: Install Alloy
      ansible.builtin.apt:
        name:
          - alloy
        state: latest
        update_cache: true

    - name: Configure alloy with templated config file
      ansible.builtin.template:
        src: ../../templates/config.alloy.j2
        dest: /etc/alloy/config.alloy
        mode: '0644'
        force: yes 
      register: alloy_config

    - name: Restart and enable alloy service
      ansible.builtin.service:
        name: alloy
        state: restarted
        enabled: yes
      when: alloy_config.changed

