---
- name: Install and self-update restic
  hosts: "{{ target_hosts | default('all') }}"
  become: true

  tasks:
    - name: Install restic
      apt:
        name: restic
        state: present

    - name: Self-update restic to latest version
      command: restic self-update

    - name: Ensure the restic backup folder exists
      file:
        path: "/var/log/ansible/restic"
        state: directory
