---
- name: Run full upgrade via apt
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Run apt update
      ansible.builtin.apt:
        update_cache: yes
      register: update_result
      failed_when: update_result.rc != 0

    - name: Upgrade the OS (apt dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist
      register: upgrade_result
      failed_when: upgrade_result.rc != 0