---
- import_playbook: ../../pve/clone_template.yml
  vars:
    vmid: "102"
    vm_name: "ansible"

- import_playbook: ../../generic/setup_network.yml
  vars:
    new_hostname: "ansible"
    new_ip: "192.168.10.22"
- import_playbook: ../../generic/update_apt.yml
  vars:
    target_hosts: ansible
- import_playbook: ../../generic/setup_alloy.yml
  vars:
    target_hosts: ansible
- import_playbook: setup_ansible.yml
- import_playbook: ../copy_crontab.yml
- import_playbook: ../../generic/reboot.yml
  vars:
    target_hosts: ansible