---
- name: Backup docker volumes to hdd
  hosts: storage
  become: yes
  vars_files:
  - ../../../vaults/auto_vault
  environment:
    RESTIC_PASSWORD: "{{ restic_docker_external_pw }}"
    RESTIC_REPOSITORY: "/mnt/external/backup/volumes/"

  tasks:
  - name: Prune the repo
    shell: restic forget --keep-last 5 --keep-daily 5 --keep-weekly 3 --keep-monthly 3 --prune > /var/log/ansible/restic/restic-docker-external-prune.log
  - name: Backup docker volumes
    shell: restic backup /mnt/ssd/volumes/ > /var/log/ansible/restic/restic-docker-external-backup.log
